version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      npm-deps:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
