name: build and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /tic-tac-toe-game
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy🚀
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: out
